[package]
name = "solders"
version = "0.1.4"
edition = "2021"
include = ["src/*.rs", "/LICENSE", "/pyproject.toml"]
description = "Python binding to the Solana Rust SDK"
license = "MIT"
repository = "https://github.com/kevinheavey/solders"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "solders"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "^0.16.4", features = ["extension-module", "abi3-py37"] }
solana-sdk = "^1.10.19"
bincode = "^1.3.3"
serde = "^1.0.136"
serde_json = "^1.0.59"
borsh = "^0.9.3"
dict_derive = "0.4.0"

[package.metadata.maturin]
python-source = "python"
