[package]
name = "solders"
version = "0.0.1"
edition = "2018"
include = ["src/*.rs", "./LICENSE", "pyproject.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "solders"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "^0.16.1", features = ["extension-module"] }
solana-sdk = "^1.10.0"
bincode = "^1.3.3"
serde = "^1.0.136"
serde_json = "^1.0.59"
borsh = "^0.9.3"
