[package]
name = "solders"
version = "0.5.2"
edition = "2021"
include = ["/src", "/LICENSE", "/pyproject.toml"]
description = "Python binding to the Solana Rust SDK"
license = "MIT"
repository = "https://github.com/kevinheavey/solders"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "solders"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module", "abi3-py37"] }
solana-sdk = "^1.14.1"
bincode = "^1.3.3"
serde = "^1.0.136"
serde_json = "^1.0.59"
borsh = "^0.9.3"
dict_derive = "0.4.0"
solders-macros = "^0.6.0"
serde_with = "^1.14.0"
base64 = "^0.13.0"
camelpaste = "0.1.0"
serde_cbor = "^0.11.2"
thiserror = "^1.0.31"
bs58 = "^0.4.0"
zstd = "0.11.2"
derive_more = "0.99.17"
