[package]
name = "solders"
version = "0.0.1"
edition = "2018"
include = ["src/lib.rs", "./LICENSE", "pyproject.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "solders"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
solana-sdk = "1.9.2"
bincode = "1.3.3"
ed25519-dalek = "1.0.1"
serde = "1.0.136"
serde_json = "1.0.59"
borsh = "0.9.3"
