[package]
name = "solders"
version = "0.14.3"
edition = "2021"
include = ["/src", "/LICENSE", "/pyproject.toml"]
description = "Python binding to the Solana Rust SDK"
license = "MIT"
repository = "https://github.com/kevinheavey/solders"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "solders"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { workspace = true, features = ["macros", "extension-module", "abi3-py37"] }
solana-sdk = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dict_derive = "0.4.0"
serde_with = { workspace = true }
base64 = { workspace = true }
camelpaste = "0.1.0"
serde_cbor = { workspace = true }
thiserror = "^1.0.31"
bs58 = "^0.4.0"
zstd = "0.11.2"
derive_more = { workspace = true }
pythonize = "0.18.0"
solders-traits = { workspace = true }
solders-macros = { workspace = true }
solders-primitives = { workspace = true }
solana-program-test = { workspace = true, optional = true }
solana-banks-client = { workspace = true, optional = true }
solana-banks-interface = { version = "1.15.2", optional = true}
tarpc = { version = "0.29.0", optional = true }
pyo3-asyncio = { version = "0.18.0", features = ["tokio-runtime"] }

[features]
program-test = [
    "dep:solana-program-test",
    "dep:solana-banks-client",
    "dep:solana-banks-interface",
    "dep:tarpc",
    "solders-traits/banks-client"
]


[workspace]
members = [".", "traits", "macros", "primitives"]

[workspace.dependencies]
pyo3 = { version = "0.18.0", default-features = false }
solders-macros = { path = "./macros", version = "0.14.3" }
solders-traits = { path = "./traits", version = "0.14.3" }
serde_with = { version = "^1.14.0", features = ["base64"] }
solders-primitives = { path = "./primitives", version = "0.14.3" }
solana-sdk = "^1.15.2"
bincode = "1.3.3"
base64 = "0.13.0"
serde = "^1.0.136"
serde_json = "^1.0.59"
serde_cbor = "^0.11.2"
derive_more = "0.99.17"
solana-program-test = "1.15.2"
solana-banks-client = "1.15.2"
