site_name: Solder
theme:
  name: material
  icon:
    logo: material/anchor
  palette:
    - scheme: default
      primary: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.snippets
  - meta
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/kevinheavey/solder
repo_name: kevinheavey/solder
site_url: https://kevinheavey.github.io/solder/
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_root_heading: true
            show_root_full_path: false
  - search
nav:
  - index.md
  - api_reference.md
extra_css:
  - css/mkdocstrings.css
