[tool.poetry]
name = "solders"
version = "0.0.1"
description = "Python bindings for Solana Rust tools"
authors = ["kevinheavey <kevinheavey123@gmail.com>"]
license = "Apache"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
maturin = "^0.12.5"
black = "^21.12b0"
wemake-python-styleguide = "^0.16.0"
mypy = "^0.930"
pytest = "^6.2.5"
pytest-benchmark = "^3.4.1"
mkdocs-material = "^8.1.3"
mkdocstrings = "^0.17.0"

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"


[project]
name = "solders"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
