[package]
name = "solders-rpc-response-data-boilerplate"
version = "0.14.4"
edition = "2021"
include = ["/src"]
license = "MIT"
repository = "https://github.com/kevinheavey/solders"

[dependencies]
solders-traits-core = { workspace = true }
