[package]
name = "solders-rpc-program-accounts-config"
version = "0.14.4"
edition = "2021"
include = ["/src"]
license = "MIT"
repository = "https://github.com/kevinheavey/solders"

[dependencies]
pyo3 = { workspace = true }
serde = { workspace = true }
solders-macros = { workspace = true }
solders-traits-core = { workspace = true }
solders-rpc-filter = { workspace = true }
solders-rpc-config-macros = { workspace = true }
solders-rpc-account-info-config = { workspace = true }
solana-rpc-client-api = { workspace = true }
