[package]
name = "solders-transaction-status-enums"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }

[dependencies]
serde = { workspace = true }
pyo3 = { workspace = true }
solana-transaction-status = { workspace = true }
solders-macros = { workspace = true }
