[package]
name = "solders-system-program"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }

[dependencies]
pyo3 = { workspace = true }
dict_derive = "0.4.0"
solders-traits-core = { workspace = true }
solders-traits = { workspace = true }
solders-instruction = { workspace = true }
solders-pubkey = { workspace = true }
solders-macros = { workspace = true }
solana-program = { workspace = true }
serde = { workspace = true }
derive_more = { workspace = true }
bincode = { workspace = true }
solana-sdk = { workspace = true }
