[package]
name = "solders-transaction-error"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }

[dependencies]
serde = { workspace = true }
solana-sdk = { workspace = true }
solders-traits-core = { workspace = true }
solders-macros = { workspace = true }
derive_more = { workspace = true }
pyo3 = { workspace = true }
