[package]
name = "solders-traits-core"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
description = "A collection of traits and helpers for Solders."
license = { workspace = true }
repository = { workspace = true }

[dependencies]
pyo3 = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_cbor = { workspace = true }
