[package]
name = "solders-rpc-requests"
version = "0.14.4"
edition = "2021"
include = ["/src"]
license = "MIT"
repository = "https://github.com/kevinheavey/solders"

[dependencies]
pyo3 = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
solders-hash = { workspace = true }
solders-macros = { workspace = true }
solders-traits-core = { workspace = true }
solders-traits = { workspace = true }
solders-commitment-config = { workspace = true }
solders-rpc-config = { workspace = true }
solders-rpc-request-params = { workspace = true }
solders-rpc-request-params-no-config = { workspace = true }
solders-rpc-version = { workspace = true }
solders-message = { workspace = true }
solders-transaction = { workspace = true }
solders-pubkey = { workspace = true }
solders-signature = { workspace = true }
camelpaste = { workspace = true }
