cargo-features = ["workspace-inheritance"]

[package]
name = "solders-traits"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
description = "A collection of traits and helpers for Solders."
license = { workspace = true }
repository = { workspace = true }

[dependencies]
pyo3 = { workspace = true }
solana-sdk = { workspace = true }
bincode = { workspace = true }
serde_json = { workspace = true }
serde_cbor = { workspace = true }
solders-traits-core = { workspace = true }
solana-banks-client = { workspace = true, optional = true }

[features]
banks-client = ["dep:solana-banks-client"]
