[package]
name = "solders-rpc-filter"
version = "0.14.4"
edition = "2021"
include = ["/src"]
license = "MIT"
repository = "https://github.com/kevinheavey/solders"

[dependencies]
pyo3 = { workspace = true }
serde = { workspace = true }
derive_more = { workspace = true }
solana-rpc-client-api = { workspace = true }
solders-macros = { workspace = true }
solders-traits-core = { workspace = true }
thiserror = { workspace = true }
bs58 = { workspace = true }
base64 = { workspace = true }
