
[package]
name = "solders-rpc-config-macros"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders RPC config macros crate."
