[package]
name = "solders-rpc-version"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }

[dependencies]
serde = { workspace = true }
