[package]
name = "solders-transaction"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders transaction crate."

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
solders-traits = { workspace = true }
solders-traits-core = { workspace = true }
solders-macros = { workspace = true }
solana-sdk = { workspace = true }
serde = { workspace = true }
derive_more = { workspace = true }
solders-message = { workspace = true }
solders-pubkey = { workspace = true }
solders-keypair = { workspace = true }
solders-signature = { workspace = true }
solders-hash = { workspace = true }
solders-instruction = { workspace = true }
