[package]
name = "solders-rpc-request-params-no-config"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders RPC request-params-no-config crate."

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
solders-commitment-config = { workspace = true }
solders-rpc-version = { workspace = true }
solders-message = { workspace = true }
solders-pubkey = { workspace = true }
solders-base64-string = { workspace = true }
